### Loops

In [1]:
n = 15
while n >= 10
    n -= 1
    println(n)
end

14
13
12
11
10
9


In [2]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [3]:
my_friends = ["John", "Daniel", "Jack", "Paul"]
for friend in my_friends
    println(string("Meet my friend $friend"))
end

Meet my friend John
Meet my friend Daniel
Meet my friend Jack
Meet my friend Paul


##### Addition Tables

In [4]:
m, n = 5, 5
A = zeros(m, n)
A

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [5]:
m, n = 5, 5
A = zeros(m, n)

for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

##### Synctactic sugar for nest for loop addition

In [6]:
m, n = 4, 5
B = zeros(m, n)

for i in 1:m, j in 1:n
    B[i, j] = i + j
end

B

4×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0
 5.0  6.0  7.0  8.0  9.0

##### Yet another way

In [7]:
m, n = 3, 3
C = [i + j for i in 1:m, j in 1:n]
C

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

##### Generating addition tables of growing size through the for loop

In [8]:
for n in 1:5
    X = [i + j for i in 1:n, j in 1:n]
    display(X)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [9]:
x = 6
y = 5

if x > y
    println("$x is greater than $y")
elseif x < y
    println("$y is greater than $x")
else
    println("$x and $y are equal")
end

6 is greater than 5


##### Ternary operator

In [10]:
a = 3
b = 4

if a > b
    a
else
    b
end

4

##### ...this is equivalent to:

In [11]:
a = 3
b = 4

(a > b) ? a : b

4

### Functions

In [12]:
function f(x)
    return(x^2)
end

f (generic function with 1 method)

In [13]:
f(2)

4

In [14]:
f2(x) = x^2
f2(8)

64

In [15]:
f2

f2 (generic function with 1 method)

### Anonymous Function

In [16]:
sayhi = name -> println("Hi $name, good to see you!")

#7 (generic function with 1 method)

In [17]:
sayhi("Anirudh")

Hi Anirudh, good to see you!


In [18]:
f3 = x -> x^3

#9 (generic function with 1 method)

In [19]:
f3(8)

512

### Duck-typing in Julia

In [20]:
sayhi(678)

Hi 678, good to see you!


In [21]:
A = rand(3,3)
A

3×3 Array{Float64,2}:
 0.800781  0.0394475  0.693362
 0.938772  0.264874   0.00279542
 0.595571  0.907955   0.0314777

This is a square of a matrix (matrix operations)

In [22]:
f(A)

3×3 Array{Float64,2}:
 1.09123  0.671579  0.577167
 1.00207  0.109729  0.651737
 1.34803  0.292568  0.416475

In [23]:
v = [3, 4, 5]

3-element Array{Int64,1}:
 3
 4
 5

The square of a vector is ambiguous

In [24]:
f(v)

MethodError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:885
  ^(!Matched::Regex, ::Integer) at regex.jl:712
  ^(!Matched::Missing, ::Integer) at missing.jl:155
  ...

### Mutating vs non-mutating functions

In [25]:
v = [3, 5, 4]

3-element Array{Int64,1}:
 3
 5
 4

##### Non-mutating

In [26]:
sort(v)

3-element Array{Int64,1}:
 3
 4
 5

In [27]:
v

3-element Array{Int64,1}:
 3
 5
 4

##### Mutating

In [28]:
sort!(v)

3-element Array{Int64,1}:
 3
 4
 5

In [29]:
v

3-element Array{Int64,1}:
 3
 4
 5

### Broadcasting

`f()` is a non-broadcasting function while `f.()` is a broadcasting function

In [30]:
A = [2*i + 3*j for i in 1:3, j in 1:3]

3×3 Array{Int64,2}:
 5   8  11
 7  10  13
 9  12  15

In [31]:
f(A)

3×3 Array{Int64,2}:
 180  252  324
 222  312  402
 264  372  480

In [32]:
f.(A)

3×3 Array{Int64,2}:
 25   64  121
 49  100  169
 81  144  225

Broadcasting `f` over a one-dimensional array is not ambiguous

In [33]:
f.(v)

3-element Array{Int64,1}:
  9
 16
 25